from pathlib import Path
from string import Template
from textwrap import dedent

import click

from mitup_bot.cli.helpers import success

DEV_CONFIG = dedent("""\
    # Generated by `uv run mitup dev`. The full catalogue of options,
    # including the optional [limits] and [patreon] sections, is documented in
    # mitup_bot/environments/sample.toml.

    [bot]
    token = "${telegram_token}"
    ${admin_tg_ids}
    [db]
    username = "mitupbot"
    database = "mitup"
    password = "12345pass"
    # "postgres" works when the bot runs inside docker compose. To run the bot on the
    # host instead, use url = "localhost" and port = 5444 (docker-compose.yaml maps
    # host port 5444 to the container's 5432).
    url = "postgres"
    port = 5432
    engine_echo = true

    [app]
    run_mode = "polling"

    [google_api]
    # Empty keys let the bot boot; location and timezone features need real API keys.
    gmaps_geocode_key = ""
    gmaps_timezone_key = ""

    [metrics]
    namespace = "MitupBot"
    environment = "rich"
    """)


def dev_toml_path() -> Path:
    return Path(__file__).parents[2] / "environments" / "dev.toml"


@click.command()
@click.argument("token", type=str)
@click.option(
    "--admin-id",
    "admin_ids",
    type=int,
    multiple=True,
    help="Telegram user id to add to bot.admin_tg_ids (repeatable). Omitted by default.",
)
@click.option("--force", is_flag=True, help="Overwrite an existing dev.toml without prompting.")
def cli(token: str, admin_ids: tuple[int, ...], force: bool):
    """
    Configure the development bot.

    This command will create a configuration file for the development bot.
    """
    target = dev_toml_path()
    if target.exists() and not force:
        click.confirm(f"{target} already exists. Overwrite it?", abort=True)

    admin_tg_ids_line = f"admin_tg_ids = {list(admin_ids)}\n" if admin_ids else ""
    target.write_text(Template(DEV_CONFIG).safe_substitute(telegram_token=token, admin_tg_ids=admin_tg_ids_line))

    success(f"Configuration file created at {target}")
