# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        exclude: (^.gitlab-ci.yml$|^mkdocs.yml$|^.gitlab/)
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/AliYmn/conventional-commits-check
    rev: v2.9.0  # Use the latest release version
    hooks:
      - id: conventional-commits-check
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: build-docs
        name: Build documentation
        entry: hatch run dev:build-docs
        language: system
        pass_filenames: false
        files: ^(docs/|mkdocs.yml)$
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: validate-locales
        name: Validate source language
        entry: hatch run dev:validate-locales
        language: system
        stages:
          - pre-push
