additional_commands:
    feat: "^Feat: "
    fix: "^Fix: "
    docs: "^Docs: "
    style: "^Style: "
    refactor: "^Refactor: "
    perf: "^Perf: "
    test: "^Test: "
    infra: "^Infra: "
    ci: "^CI: "
    chore: "^Chore: "
    revert: "^Revert: "
    merge: "^Merge: "
    update: "^Update: "
    monitoring: "^Monitoring: "
    wip: "^WIP"
    copy: "^Copy: "

additional_emojis:
    feat: "✨"
    fix: "🐛"
    docs: "📚"
    style: "💎"
    refactor: "🧹"
    update: "🚀"
    perf: "🚀"
    test: "🧪"
    infra: "🏗️"
    monitoring: "📈"
    ci: "👷"
    chore: "♻️"
    revert: "⏪"
    merge: "🔀"
    wip: "⏳"
    copy: "🗣️"
