aditional_commands:
    feat: "^feat(\\(.+\\))?:"
    fix: "^fix(\\(.+\\))?:"
    docs: "^docs(\\(.+\\))?:"
    style: "^style(\\(.+\\))?:"
    refactor: "^refactor(\\(.+\\))?:"
    perf: "^perf(\\(.+\\))?:"
    test: "^test(\\(.+\\))?:"
    infra: "^infra(\\(.+\\))?:"
    ci: "^ci(\\(.+\\))?:"
    chore: "^chore(\\(.+\\))?:"
    revert: "^revert: "

aditional_emojis:
    feat: "✨"
    fix: "🐛"
    docs: "📚"
    style: "💎"
    refactor: "🧹"
    perf: "🚀"
    test: "🧪"
    infra: "🏗️"
    ci: "👷"
    chore: "♻️"
    revert: "⏪"
    merge: "🔀"
