files:
  - source: /mitup_bot/locales/en.po
    translation: /mitup_bot/locales/%locale_with_underscore%.po
commit_message: '🗣️ translations: [skip ci] Translations from Crowdin, (%language%)'
append_commit_message: false
