services:
  run-tests:
    build:
      dockerfile: ./dev/docker/Dockerfile.dev
    volumes:
      - .:/bot
    command: hatch run dev:test

  migrations-upgrade: &migrations-service
    # Intended only for local migrations
    build:
      dockerfile: ./dev/docker/Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - .:/bot
      - ./.docker_hatch:/.docker_hatch
    environment:
      - MITUPBOT__DB__USERNAME=mitupbot
      - MITUPBOT__DB__PASSWORD=12345pass
      - MITUPBOT__DB__DATABASE=mitup
      - MITUPBOT__DB__URL=postgres
      - MITUPBOT__DB__PORT=5432
    command: hatch run dev:migrations-upgrade

  migrations-downgrade:
    # Intended only for local migrations
    <<: *migrations-service
    command: hatch run dev:migrations-downgrade

  postgres:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: mitupbot
      POSTGRES_PASSWORD: 12345pass
      POSTGRES_DB: mitup
    ports:
      - 5444:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mitup: &launch-bot
    depends_on:
      - postgres
    build:
      dockerfile: ./dev/docker/Dockerfile.dev
    environment:
      - MITUPBOT__METRICS__ENVIRONMENT=rich
      - MITUPBOT__METRICS__NAMESPACE=MitupDocker
    volumes:
      - .:/bot
      - ./.docker_hatch:/.docker_hatch
    command: bash -c "hatch run dev:update-locales && hatch run dev:launch"

  debug:
    <<: *launch-bot
    command: hatch run dev:debug
    ports:
      - 5678:5678

  events:
    <<: *launch-bot
    command: bash -c "hatch run dev:update-locales && hatch run dev:launch-events --notify-meeting-interval 5 --user-cleanup-interval 10 --generate-stats-interval 5 --env dev"
    environment:
      - MITUPBOT__METRICS__ENVIRONMENT=rich
      - MITUPBOT__METRICS__NAMESPACE=MitupDocker/RecurrentEvents
