[project]
name = "mitup-telegram-bot"
dynamic = ["version"]
description = "Telegram social bot to manage your meetings"
licence = "MIT"
requires-python = ">=3.11"
authors = [
  { name = "Enrique Araque", email = "minixute@gmail.com" },
  { name = "Juanpe Araque", email = "erjuanpea@gmail.com" }
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Programming Language :: Python :: 3.12",
  "Framework :: FastAPI",
  "Framework :: Hatch",
  "Topic :: Communications :: Chat"
]
dependencies = [
  "python-telegram-bot"
]

[project.urls]
Source = "https://gitlab.com/meetupbot/mitup-telegram-bot"
Documentation = "https://gitlab.com/meetupbot/mitup-telegram-bot/-/blob/main/README.md"
Issues = "https://gitlab.com/meetupbot/mitup-telegram-bot/-/issues"

[tool.isort]
profile = "black"
src_paths = ["mitup_bot", "tests"]
skip = [".hatch"]
color_output = true

[tool.hatch.version]
path = "mitup_bot/__about__.py"

# --------------------------
# Development/CI environment
# --------------------------
[tool.hatch.envs.dev]
description = """
Enviroment to be used for bot testing
"""
dependencies = [
  "pytest~=7.3",
  "pytest-asyncio~=0.21",
  "pytest-cov~=4.1",
  "black~=23.7",
  "isort[colors]~=5.0"
]

[tool.hatch.envs.dev.scripts]
test = "pytest --cov=mitup_bot --cov-report term tests/"
test-cov = "pytest --cov=mitup_bot --cov-report term tests/ --cov-report xml:coverage.xml --junitxml=report.xml"
format = [
  "black .",
  "isort ."
]
format-check = [
  "black --check .",
  "isort --check-only ."
]

# ----------------------
# Production environment
# ----------------------

[tool.hatch.envs.production.scripts]
bot = "python mitup_bot/launch.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"