[project]
name = "mitup-telegram-bot"
dynamic = ["version"]
description = "Telegram social bot to manage your meetings"
licence = "MIT"
requires-python = ">=3.11"
authors = [
    { name = "Enrique Araque", email = "minixute@gmail.com" },
    { name = "Juanpe Araque", email = "erjuanpea@gmail.com" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3.12",
    "Framework :: FastAPI",
    "Framework :: Hatch",
    "Topic :: Communications :: Chat"
]
dependencies = [
    "python-telegram-bot~=20.0",
    "click~=8.0",
    "python-dateutil",
    "sqlalchemy~=1.4",
    "alembic~=1.6",
    "psycopg2~=2.9",
    "sqlmodel",
    "sqlalchemy~=1.4",
    "alembic~=1.6",
    "python-dateutil",
    "rich~=13.0",
]

[project.urls]
Source = "https://gitlab.com/meetupbot/mitup-telegram-bot"
Documentation = "https://gitlab.com/meetupbot/mitup-telegram-bot/-/blob/main/README.md"
Issues = "https://gitlab.com/meetupbot/mitup-telegram-bot/-/issues"

[tool.hatch.version]
path = "mitup_bot/__about__.py"

[tool.isort]
profile = "black"
src_paths = ["mitup_bot", "tests"]
skip = [".hatch"]
color_output = true

# Global pytest setup, mainline to run from VSCode
# Cannot launch VSCode tests/debug with cov plugin
[tool.pytest.ini_options]
addopts = "-ra"
testpaths = "tests"
asyncio_mode = "auto"

[tool.mypy]
exclude = "conftest.py"

[tool.coverage.run]
branch = true

[tool.coverage.report]
omit = [
    # Don't run coverage bon bin scripts. These are scripts that are not forced to be tested as they
    # have no impact in production and mainly helper scripts
    "bin",
    "__about__.py",
]
exclude_also = [
    # Exclude protocol classes since they have no logic
    "class .*\\bProtocol\\):"
]

# --------------------------
# Development/CI environment
# --------------------------
[tool.hatch.envs.dev]
description = """
Enviroment to be used for bot testing
"""
dependencies = [
    "pytest~=7.3",
    "pytest-asyncio~=0.21",
    "pytest-cov~=4.1",
    "black~=23.7",
    "isort[colors]~=5.0",
    "flake8",
    "mypy~=1.0",
    "pytest-asyncio",
    "freezegun"
]

[tool.hatch.envs.dev.scripts]
test = "pytest --cov=mitup_bot --cov-report term-missing:skip-covered tests"
test-cov = "pytest --cov=mitup_bot --cov-report term-missing:skip-covered tests/ --cov-report xml:coverage.xml --junitxml=report.xml"
format = [
    "black .",
    "isort ."
]
format-check = [
    "black --check .",
    "isort --check-only ."
]
lint = "flake8 ."
type-check = "mypy tests mitup_bot bin"
validate = [
    "test",
    "format-check",
    "lint",
    "type-check",
]
setup-vscode = "python bin/setup_vscode.py"
migrations-upgrade = "alembic upgrade head"
migrations-downgrade = "alembic downgrade -1"
launch = "python -m mitup_bot.cli.launch"


# ----------------------
# Production environment
# ----------------------

[tool.hatch.envs.production.scripts]
launch = "python -m mitup_bot.cli.launch --env prod"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"