import shutil
import subprocess
from pathlib import Path
from string import Template
from textwrap import dedent
from typing import Annotated

import typer

from . import console, runner, vscode

LOCAL_ONLY_FILES = (".env", ".envrc")

DEV_CONFIG = dedent("""\
    # Generated by `uv run mb setup --bot-token`. The full catalogue of options,
    # including the optional [limits] and [patreon] sections, is documented in
    # libs/core/mitup_bot/environments/sample.toml.

    [bot]
    token = "${telegram_token}"
    ${admin_tg_ids}
    [db]
    username = "mitupbot"
    database = "mitup"
    password = "12345pass"
    # "postgres" works when the bot runs inside docker compose. To run the bot on the
    # host instead, use url = "localhost" and port = 5444 (docker-compose.yaml maps
    # host port 5444 to the container's 5432).
    url = "postgres"
    port = 5432
    engine_echo = true

    [app]
    run_mode = "polling"

    [google_api]
    # Empty keys let the bot boot; location and timezone features need real API keys.
    gmaps_geocode_key = ""
    gmaps_timezone_key = ""

    [metrics]
    namespace = "MitupBot"
    environment = "rich"
    """)


def main_checkout_root() -> Path:
    """Return the main checkout's root; in a worktree, `--git-common-dir` points into the main clone."""
    result = subprocess.run(
        ["git", "rev-parse", "--git-common-dir"],
        capture_output=True,
        text=True,
        check=True,
        cwd=runner.repo_root(),
    )
    return Path(result.stdout.strip()).resolve().parent


def copy_local_only_files(main_root: Path, current_root: Path) -> list[str]:
    """Copy untracked local config from the main checkout, never overwriting existing files."""
    if main_root == current_root:
        return []
    copied: list[str] = []
    for name in LOCAL_ONLY_FILES:
        source = main_root / name
        target = current_root / name
        if source.is_file() and not target.exists():
            shutil.copy(source, target)
            copied.append(name)
    return copied


def dev_toml_path() -> Path:
    """Resolve environments/dev.toml from the installed package — the same directory `Config`
    reads via `importlib.resources.files`, so the write path cannot drift from the read path.
    """
    # Imported lazily so a plain `mb` invocation doesn't pull in the bot package just to resolve
    # a path it will not use.
    from importlib.resources import files

    from mitup_bot import environments

    return Path(str(files(environments))) / "dev.toml"


def write_dev_config(token: str, admin_ids: tuple[int, ...], force: bool):
    """Write the local development bot configuration to environments/dev.toml."""
    target = dev_toml_path()
    if target.exists() and not force:
        typer.confirm(f"{target} already exists. Overwrite it?", abort=True)

    admin_tg_ids_line = f"admin_tg_ids = {list(admin_ids)}\n" if admin_ids else ""
    target.write_text(Template(DEV_CONFIG).safe_substitute(telegram_token=token, admin_tg_ids=admin_tg_ids_line))
    console.success(f"Configuration file created at {target}")


def setup_command(
    bot_token: Annotated[
        str | None,
        typer.Option("--bot-token", help="Telegram bot token to write into environments/dev.toml."),
    ] = None,
    admin_ids: Annotated[
        list[int] | None,
        typer.Option("--admin-id", help="Telegram user id to add to bot.admin_tg_ids (repeatable)."),
    ] = None,
    force: Annotated[bool, typer.Option("--force", help="Overwrite an existing dev.toml without prompting.")] = False,
    setup_vscode: Annotated[
        bool, typer.Option("--vscode", help="Also generate the VS Code workspace settings.")
    ] = False,
):
    """Bootstrap this checkout: local config files, dependencies, and git hooks. Idempotent.

    Pass --bot-token to also write the local development bot configuration (dev.toml).
    """
    if bot_token is not None:
        write_dev_config(bot_token, tuple(admin_ids or ()), force)
    current_root = runner.repo_root()
    for name in copy_local_only_files(main_checkout_root(), current_root):
        console.info(f"Copied {name} from the main checkout.")
    sync_exit = runner.run_step("Installing dependencies (uv sync)", ["uv", "sync"])
    if sync_exit != 0:
        raise typer.Exit(sync_exit)
    if shutil.which("pre-commit"):
        hooks_exit = runner.run_step("Installing git hooks (pre-commit)", ["pre-commit", "install"])
        if hooks_exit != 0:
            raise typer.Exit(hooks_exit)
    else:
        console.warn("pre-commit not found — skipping git hook installation.")
    if setup_vscode:
        raise typer.Exit(vscode.apply_vscode_settings())
    console.success("Checkout ready.")
