import json
import shutil
import subprocess
import sys
import textwrap
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, Annotated

import typer

from . import console, runner, vscode

if TYPE_CHECKING:  # pragma: no cover
    from pydantic import BaseModel
    from pydantic.fields import FieldInfo

    from mitup_bot.config import Sample

LOCAL_ONLY_FILES = (".env", ".envrc")

DEV_CONFIG_HEADER = (
    "# Generated by `uv run mb setup`. Rerun it any time to fill in newly required options while\n"
    "# keeping the values already set. The full catalogue of options, including every optional\n"
    "# field, is documented on the config models in libs/core/mitup_bot/config.py.\n"
)

Overrides = dict[str, dict[str, object]]


def main_checkout_root() -> Path:
    """Return the main checkout's root; in a worktree, `--git-common-dir` points into the main clone."""
    result = subprocess.run(
        ["git", "rev-parse", "--git-common-dir"],
        capture_output=True,
        text=True,
        check=True,
        cwd=runner.repo_root(),
    )
    return Path(result.stdout.strip()).resolve().parent


def copy_local_only_files(main_root: Path, current_root: Path) -> list[str]:
    """Copy untracked local config from the main checkout, never overwriting existing files."""
    if main_root == current_root:
        return []
    copied: list[str] = []
    for name in LOCAL_ONLY_FILES:
        source = main_root / name
        target = current_root / name
        if source.is_file() and not target.exists():
            shutil.copy(source, target)
            copied.append(name)
    return copied


def dev_toml_path() -> Path:
    """Resolve environments/dev.toml from the installed package — the same directory `Config`
    reads via `importlib.resources.files`, so the write path cannot drift from the read path.
    """
    # Imported lazily so a plain `mb` invocation doesn't pull in the bot package just to resolve
    # a path it will not use.
    from importlib.resources import files

    from mitup_bot import environments

    return Path(str(files(environments))) / "dev.toml"


def required_sections() -> dict[str, type[BaseModel]]:
    """The `Config` sections a dev.toml must contain, in model declaration order."""
    from pydantic import BaseModel

    from mitup_bot.config import Config

    sections: dict[str, type[BaseModel]] = {}
    for name, field in Config.model_fields.items():
        if not field.is_required():
            continue
        assert isinstance(field.annotation, type) and issubclass(field.annotation, BaseModel), (
            f"Required config section [{name}] must be annotated with a BaseModel subclass"
        )
        sections[name] = field.annotation
    return sections


def field_sample(field: FieldInfo) -> Sample | None:
    from mitup_bot.config import Sample

    return next((meta for meta in field.metadata if isinstance(meta, Sample)), None)


def toml_literal(value: object) -> str:
    match value:
        case bool():
            return "true" if value else "false"
        case str() | list():
            # JSON string and array syntax is valid TOML for these shapes.
            return json.dumps(value)
        case int() | float():
            return str(value)
        case _:
            raise TypeError(f"Unsupported TOML value {value!r} ({type(value).__name__})")


def comment_lines(comment: str) -> list[str]:
    return [f"# {line}" for line in textwrap.wrap(comment, width=98)]


def section_entries(
    section: str,
    model: type[BaseModel],
    overrides: dict[str, object] | None = None,
    skip: set[str] | frozenset[str] = frozenset(),
    required_only: bool = False,
) -> list[str]:
    """TOML entry lines for one section: every field carrying a `Sample` or an override.

    A required field with neither is a hard error — it would generate a dev.toml the bot
    cannot boot from, so the gap must be fixed in `mitup_bot.config` instead of shipped.
    """
    overrides = overrides or {}
    lines: list[str] = []
    for name, field in model.model_fields.items():
        if name in skip or (required_only and not field.is_required()):
            continue
        sample = field_sample(field)
        if name in overrides:
            value = overrides[name]
        elif sample is not None:
            value = sample.value
        elif field.is_required():
            raise RuntimeError(
                f"Required config field [{section}] {name} has no Sample annotation; "
                "add one in mitup_bot.config so `mb setup` can generate a value for it."
            )
        else:
            continue
        if sample is not None and sample.comment:
            lines.extend(comment_lines(sample.comment))
        lines.append(f"{name} = {toml_literal(value)}")
    return lines


def render_dev_config(overrides: Overrides) -> str:
    blocks = [DEV_CONFIG_HEADER]
    for section, model in required_sections().items():
        entries = section_entries(section, model, overrides=overrides.get(section))
        blocks.append("\n".join([f"[{section}]", *entries]) + "\n")
    return "\n".join(blocks)


def write_dev_config(token: str, admin_ids: tuple[int, ...], force: bool):
    """Write the local development bot configuration to environments/dev.toml."""
    target = dev_toml_path()
    if target.exists() and not force:
        typer.confirm(f"{target} already exists. Overwrite it?", abort=True)

    bot_overrides: dict[str, object] = {"token": token}
    if admin_ids:
        bot_overrides["admin_tg_ids"] = list(admin_ids)
    target.write_text(render_dev_config({"bot": bot_overrides}))
    console.success(f"Configuration file created at {target}")


def insert_section_entries(lines: list[str], section: str, entries: list[str]):
    """Insert entry lines right below the `[section]` header, leaving the rest untouched."""
    header_index = next(index for index, line in enumerate(lines) if line.split("#")[0].strip() == f"[{section}]")
    lines[header_index + 1 : header_index + 1] = entries


def entry_keys(entries: list[str]) -> list[str]:
    return [line.split(" = ")[0] for line in entries if not line.startswith("#")]


def warn_if_config_invalid(target: Path):
    """A refreshed dev.toml is structurally complete, but the values the user had set may still be
    invalid — surface that now instead of letting the next bot start be the discovery."""
    from pydantic import ValidationError

    from mitup_bot.config import Config

    try:
        Config.model_validate(tomllib.loads(target.read_text()))
    except ValidationError as error:
        console.warn(f"{target} still fails config validation:\n{error}")


def refresh_dev_config():
    """Add every missing required option to an existing dev.toml, preserving all set values."""
    target = dev_toml_path()
    try:
        existing = tomllib.loads(target.read_text())
    except tomllib.TOMLDecodeError as error:
        console.warn(f"{target} is not valid TOML ({error}); fix it or regenerate with --bot-token --force.")
        raise typer.Exit(1) from error

    lines = target.read_text().splitlines()
    added: list[str] = []
    for section, model in required_sections().items():
        if section not in existing:
            entries = section_entries(section, model)
            lines.extend(["", f"[{section}]", *entries])
            added.extend(f"{section}.{key}" for key in entry_keys(entries))
            continue
        entries = section_entries(section, model, skip=set(existing[section]), required_only=True)
        if entries:
            insert_section_entries(lines, section, entries)
            added.extend(f"{section}.{key}" for key in entry_keys(entries))

    if not added:
        console.success(f"{target} already covers every required option.")
        return
    target.write_text("\n".join(lines) + "\n")
    console.success(f"Added missing options to {target}: {', '.join(added)}")
    warn_if_config_invalid(target)


def stdin_is_interactive() -> bool:
    return sys.stdin.isatty()


def prompt_for_dev_config():
    """First run on a fresh checkout: offer to create dev.toml on the spot.

    Only prompts on an interactive terminal so scripted and CI invocations never hang."""
    if not stdin_is_interactive():
        console.info("No dev.toml found. Create one with `uv run mb setup --bot-token <token>`.")
        return
    token = typer.prompt(
        "No dev.toml found. Telegram bot token from @BotFather (leave empty to skip)",
        default="",
        show_default=False,
    ).strip()
    if token:
        write_dev_config(token, (), force=True)
    else:
        console.info("Skipped. Create it later with `uv run mb setup --bot-token <token>`.")


def setup_command(
    bot_token: Annotated[
        str | None,
        typer.Option("--bot-token", help="Telegram bot token to write into environments/dev.toml."),
    ] = None,
    admin_ids: Annotated[
        list[int] | None,
        typer.Option("--admin-id", help="Telegram user id to add to bot.admin_tg_ids (repeatable)."),
    ] = None,
    force: Annotated[bool, typer.Option("--force", help="Overwrite an existing dev.toml without prompting.")] = False,
    setup_vscode: Annotated[
        bool, typer.Option("--vscode", help="Also generate the VS Code workspace settings.")
    ] = False,
):
    """Bootstrap this checkout: local config files, dependencies, and git hooks. Idempotent.

    Pass --bot-token to write the local development bot configuration (dev.toml) from scratch.
    Without it, an existing dev.toml is refreshed in place: every required option it is missing
    is added with a sample value, and every value already set is left untouched. With neither a
    token nor an existing dev.toml, an interactive run asks for the token.
    """
    if bot_token is not None:
        write_dev_config(bot_token, tuple(admin_ids or ()), force)
    elif dev_toml_path().exists():
        refresh_dev_config()
    else:
        prompt_for_dev_config()
    current_root = runner.repo_root()
    for name in copy_local_only_files(main_checkout_root(), current_root):
        console.info(f"Copied {name} from the main checkout.")
    sync_exit = runner.run_step("Installing dependencies (uv sync)", ["uv", "sync"])
    if sync_exit != 0:
        raise typer.Exit(sync_exit)
    if shutil.which("pre-commit"):
        hooks_exit = runner.run_step("Installing git hooks (pre-commit)", ["pre-commit", "install"])
        if hooks_exit != 0:
            raise typer.Exit(hooks_exit)
    else:
        console.warn("pre-commit not found — skipping git hook installation.")
    if setup_vscode:
        raise typer.Exit(vscode.apply_vscode_settings())
    console.success("Checkout ready.")
