from enum import Enum


class Emojis(Enum):
    # FLAGS
    FLAG_BR = "🇧🇷"
    FLAG_ES = "🇪🇸"
    FLAG_US = "🇺🇸"
    FLAG_DE = "🇩🇪"
    FLAG_IT = "🇮🇹"

    # Symbols
    CLOCK = "🕒"
    PROHIB = "🚫"
    MAP = "🗺️"
    PEOPLE = "👥"
    DESCRIPTION = "📄"
    IMAGES = "🖼️"
    USER_WAITING = "📝"
    LOCK = "🔒"
    CALENDAR = "🗓️"
    TITLE = "🅰️"
    PIN = "📍"
    HOME = "🏠"
    CHECK = "✅"
    CANCEL = "❌"
    DELETE = "🗑️"
    EDIT = "✏️"
    SHARE = "📨"
    SPARKLES = "✨"
    RED_CIRCLE = "🔴"
    GREEN_CIRCLE = "🟢"
    NEW_MEETING = "➕"
    LIST = "📂"
    PAST = "💾"
    JOINED = "👥"
    SETTINGS = "⚙️"
    CONTROLS = "🎛️"
    TOOLS = "🛠️"
    HELP = "❓"
    BOOK = "📖"
    CHART = "📊"
    MAIL = "✉️"
    NEWS = "📣"
    HEART = "♥"
    HANDSHAKE = "🤝"
    LINK = "🔗"
    DONATE = "💶"
    # Per-tier supporter badges: coffee, dice, and trophy.
    HOST_1 = "☕️"
    HOST_2 = "🎲"
    HOST_3 = "🏆"
    REPLY = "▶"
    REPLY_ALL = "⏩"
    ACTIVATE = "🔄"
    TIME = "🌐"
    ATTACH = "⬇"
    DEATTACH = "⬆"
    SEARCH = "🔍"
    HOURGLASS = "⌛"
    WARNING = "⚠️"
    NOTIF = "⏰"
    LANG = "🔣"
    WAITING = "😴"
    PUBLIC = "🌎"
    SHIELD = "🛡️"
    FRIEND = "😄"
    GLASSES = "🕶"
    CLIP = "📎"
    PACKAGE = "📦"
    PHONE = "📱"
    THINK = "🤔"
    UFO = "🛸"
    GIFT = "🎁"
    BRAIN = "🧠"
    ROCKET = "🚀"
    START = "▶️"

    def __str__(self):
        return self.value

    @classmethod
    def boolean(cls, value: bool) -> str:
        return cls.CHECK.value if value else cls.RED_CIRCLE.value
