# Thid Dockerfile is used to generate the docker image used to run a lambda
# that runs migrations in RDS.
# It uses the lambda image that contains the python runtime and the lambda
# setup to be able to call the handler when a lambda is launched
FROM public.ecr.aws/lambda/python:3.13

# Install libraries needed to run pyscopg2
RUN dnf install -y libpq-devel gcc \
    && dnf clean all \
  	&& rm -rf /var/cache/yum

# Install Hatch
RUN pip install hatch

# Copy bot into container. LAMBDA_TASK_ROOT is an environment variable
# defined by the lambda image and points to where the lambda code
# will be executed from
COPY mitup_bot ${LAMBDA_TASK_ROOT}/mitup_bot
COPY alembic.ini ${LAMBDA_TASK_ROOT}/alembic.ini
COPY pyproject.toml ${LAMBDA_TASK_ROOT}/pyproject.toml
COPY LICENSE ${LAMBDA_TASK_ROOT}/LICENSE

# Build the project
RUN hatch build -t wheel

# Install the proejct
RUN pip install ${LAMBDA_TASK_ROOT}/$(ls -1 dist/*whl)

# The CMD needs to be set to the lambda handler
CMD ["mitup_bot.lambdas.recurrent_lambda.lambda_handler"]
