# This Dockerfile builds an image that includes the Python:3.12 image
# with Hatch to allow executing pipeline jobs.
# The image is build by a manual job in any pipeline
FROM python:3.11-slim-bookworm

# Install Hatch
RUN pip install hatch